# Generated by Django 2.2 on 2019-04-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
