# Generated by Django 2.2 on 2019-04-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadmin', '0002_auto_20190428_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
    ]
