# Generated by Django 2.2 on 2019-04-29 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gadmin', '0005_auto_20190428_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='con_store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gadmin.StoreInfo', verbose_name='所属仓库'),
        ),
    ]
