# Generated by Django 2.2 on 2019-04-29 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadmin', '0006_auto_20190429_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeinfo',
            options={'verbose_name': '仓库信息', 'verbose_name_plural': '仓库信息'},
        ),
    ]
