# Generated by Django 2.2 on 2019-04-29 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gadmin', '0007_auto_20190429_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': '零件信息', 'verbose_name_plural': '零件信息'},
        ),
        migrations.AlterModelOptions(
            name='typeinfo',
            options={'verbose_name': '零件种类', 'verbose_name_plural': '零件种类'},
        ),
        migrations.AlterField(
            model_name='goods',
            name='goodstype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gadmin.TypeInfo', verbose_name='商品'),
        ),
    ]
