# Generated by Django 2.2 on 2019-04-29 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gadmin', '0008_auto_20190429_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gadmin.StoreInfo', verbose_name='所属仓库'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goodstype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gadmin.TypeInfo', verbose_name='商品种类'),
        ),
    ]
